
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.board_core_file=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.console=n
CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_HAS_PRJSEG_module.board.peripheral_sel=n
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
CONFIG_MCUX_COMPONENT_driver.romapi=n
CONFIG_MCUX_COMPONENT_driver.clock=n
CONFIG_MCUX_COMPONENT_driver.edma_soc=n
CONFIG_MCUX_COMPONENT_driver.inputmux_connections=n
CONFIG_MCUX_COMPONENT_driver.reset=n
CONFIG_MCUX_COMPONENT_driver.trdc_soc=n
CONFIG_MCUX_COMPONENT_driver.common=n
CONFIG_MCUX_COMPONENT_driver.gpio=n
CONFIG_MCUX_COMPONENT_driver.lpuart=n
CONFIG_MCUX_COMPONENT_driver.mcx_spc=n
CONFIG_MCUX_COMPONENT_driver.port=n

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION
CONFIG_MCUX_COMPONENT_driver.common=y
CONFIG_MCUX_COMPONENT_driver.glikey=y
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION
CONFIG_MCUX_COMPONENT_driver.mcx_cmc=y
CONFIG_MCUX_COMPONENT_driver.mcx_spc=y
CONFIG_MCUX_COMPONENT_driver.port=y
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION
CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_COMPONENT_driver.reset=y
CONFIG_MCUX_COMPONENT_driver.glikey=n
CONFIG_MCUX_COMPONENT_driver.mcx_cmc=n
# END AUTO-ADDED BY MCUXPRESSO EXTENSION
