CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_COMPONENT_device.system=y
CONFIG_MCUX_COMPONENT_device.startup=y
CONFIG_MCUX_COMPONENT_utilities.misc_utilities=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.clock=n
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.board_core_file=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.clock_board_folder=n
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_core1=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_core_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.use_board_peripheral=n
CONFIG_MCUX_PRJSEG_module.use_customize_peripheral=y
CONFIG_MCUX_PRJSEG_project.hw_project_core_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_core0=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_core0=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.clock_board_core_folder=n
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_core1=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.console=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y